### ISSUE TITLE
编辑器的图片上传报错

### ISSUE THREAD

**Issue by bangq** [fairyhawk/imageUpload#1]
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://www.axy.com" from accessing a cross-origin frame.
    at Function._iframeDoc [as iframeDoc] (http://www.axy.com/js/kindeditor/kindeditor-all.js:3522:15)
    at HTMLIFrameElement.<anonymous> (http://www.axy.com/js/kindeditor/kindeditor-all.js:4189:16)
    at Function.<anonymous> (http://www.axy.com/js/kindeditor/kindeditor-all.js:463:12)
    at _each (http://www.axy.com/js/kindeditor/kindeditor-all.js:57:11)
    at HTMLIFrameElement.events.(anonymous function) (http://www.axy.com/js/kindeditor/kindeditor-all.js:461:4)

**Comment by bangq** [comment]
csdn 有一篇博客应该也是大神写的吧，可以正常的返回下面的 字符串：
redirect:http://www.axy.com/js/kindeditor/plugins/image/redirect.html?s={"url":"//attached/image/20170824/20170824235941_7775.png","error":0}#{"url":"//attached/image/20170824/20170824235941_7775.png","error":0}

但是传了之后没有翻译
